-- Update structure OSZContractItem

ALTER TABLE `OSZContractItem2011` ADD `contractfrom` DATE DEFAULT NULL ,
ADD `contractto` DATE DEFAULT NULL ,
ADD `hours` VARCHAR( 5 ) NOT NULL ,
ADD `value` DOUBLE NOT NULL DEFAULT '0',
ADD `pio` DOUBLE NOT NULL DEFAULT '0',
ADD `health` DOUBLE NOT NULL DEFAULT '0',
ADD `insurance` DOUBLE NOT NULL DEFAULT '0',
ADD `bruto` DOUBLE NOT NULL DEFAULT '0';

ALTER TABLE `OSZInvoice2011` ADD `rule` TINYINT NOT NULL DEFAULT '0';

ALTER TABLE `OSZInvoiceContractItem2011` ADD `pio` DOUBLE NOT NULL DEFAULT '0',
ADD `health` DOUBLE NOT NULL DEFAULT '0',
ADD `insurance` DOUBLE NOT NULL DEFAULT '0',
ADD `bruto` DOUBLE NOT NULL DEFAULT '0';

ALTER TABLE `OSZCooperative` ADD `short` VARCHAR( 50 ) NOT NULL AFTER `name` ,
ADD `shortest` VARCHAR( 25 ) NOT NULL AFTER `short`;

ALTER TABLE `OSZCooperative` ADD `contracthours` TINYINT NOT NULL DEFAULT '0',
ADD `memberhours` TINYINT NOT NULL DEFAULT '0'; 

ALTER TABLE `OSZContract2011` ADD `net` DOUBLE NOT NULL DEFAULT '0',
ADD `tax` DOUBLE NOT NULL DEFAULT '0',
ADD `contribute` DOUBLE NOT NULL DEFAULT '0',
ADD `claimsum` DOUBLE NOT NULL DEFAULT '0',
ADD `sum` DOUBLE NOT NULL DEFAULT '0',
ADD `rule` TINYINT NOT NULL DEFAULT '0';
